typography_spectrum: 0.13302508858032525
content_rating:
  adult: false
color:
  brandStrength: 0.1991130264941603
  lightness: 0.024850087240338326
  saturation: 0.9435874717310071
  rhythmicContrast: 0.6279780883342028
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.04809064930304885
author:
  name: Oral I.L. Selver
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/be1194e5-608a-477f-8745-f8453d0698a8.png
name: Executive Realty TCI
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e47f0bb-4362-42ae-9825-5811b07b18cd.png
title: Executive Realty TCI
