layout_spectrum: 0.8031570790335536
typography_spectrum: 0.8688817461952567
color:
  brandStrength: 0.1494556984398514
  lightness: 0.7248320053331554
  saturation: 0.5997660474386066
  rhythmicContrast: 0.9075985322706401
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Executive Realty\
